### ISSUE TITLE
Scaffold edit will not update crop

### ISSUE THREAD

**Issue by vjandrei** [evg2108/carrierwave-crop-on-fly#2]
Hi, I have issue when try to update(edit) scaffold crop image it will not update the image.
I have used the crop-on-fly here http://46.101.120.93/
Do I need profiles_controller.rb define the crop? https://github.com/vjandrei/rails4_snappaajat/blob/DeployTestCapistrano/app/controllers/profiles_controller.rb

**Comment by evg2108** [comment]
Sorry, but in this version you can't edit image, you can only upload new image. Maybe i implemet this in next version.

And pay attention please, my gem based on carrierwave-crop gem but it not a fork, and it has different behavior. That's why if you use my gem you shouldn't use carrierwave-crop documentation.

**Comment by vjandrei** [comment]
All right, so you can only edit one time. 
It would be nice to have the edit option. All right, thanks.
